### PR TITLE
Blog app - Views

### PR DESCRIPTION
**Pull request by marurevi**
## Blog app - Views
In this PR I implement the following features following the design from the sneak peek wireframes.
- Create Index and Show files for users on View folder
- Create Index and Show files for posts on View folder
- Implement partials for both folders in view
**Users#Index**

image

**Users#show**

image

**Posts#Index**
image

**Posts#show**
image

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @marurevi,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- Linters are green ✅.
- PR is very detailed ✅.
- The readme file is very good ✅.
- Commit messages are consitent.

## Required Changes ♻️
_Check the comments under the review._

- **Nice job on the views but the app is not rendering the `posts or the comments` so please that issue and resubmit again**
 
Capture d’écran 2022-08-18 083221
Capture d’écran 2022-08-18 083241


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by marurevi** [comment]
@dasileker Hello, Do you check the url `/users`? Maybe that is the issue. 🤔

**Comment by dasileker** [comment]
Hello,  as you see the user part Is working fine but the post and  comments are  not se the first  screen shot is the user the second is post.

**Comment by marurevi** [comment]
> Hello,  as you see the user part Is working fine but the post and  comments are  not se the first  screen shot is the user the second is post. 

Oh, I see. Could it be posible that the db is empty? Could you please check again runing rails db:seed? 🙏☺

**Comment by dasileker** [comment]
No it's not the seed, I will give a hint it's the user index#show it has something incorrect to render the posts.

**Comment by marurevi** [comment]
> No it's not the seed, I will give a hint it's the user index#show it has something incorrect to render the posts. 

Ok, thanks! I'll check it again  🙂👍

**Comment by marurevi** [comment]
> > No it's not the seed, I will give a hint it's the user index#show it has something incorrect to render the posts.
> 
> Ok, thanks! I'll check it again 🙂👍

**Review by descholar-ceo — APPROVED** [review]
Hi @marurevi 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 You implemented all requested changes ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
